db:
  driver: mysql
postgres:
  dsn: host=127.0.0.1 user=postgres password=yourpassword dbname=yourdb port=5432 sslmode=disable
mysql:
  dsn: root:12345678@tcp(localhost:3306)/flowing?charset=utf8mb4&parseTime=True&loc=Local
redis:
  host: localhost
  port: 6379
  password:
  db: 0
server:
  port: 8585
logger:
  format: json
  level: debug
  path:
jwt:
  secret: abcd1234
fileStore: minio
minio:
  endpoint: localhost:9000
  accessKey: minioadmin
  secretKey: 12345678
  bucket: flowingdocs
worker: gopool
gopool:
  size: 16
  timeout: 300s
knowledge_graph:
  entityPrompt: |
    ## 任务
        用户提供的文本中，提取所有符合以下实体类型的实体：
        EntityTypes: [Person, Organization, Location, Product, Event, Date, Work, Concept, Resource, Category, Operation]

        ## 要求
        1. 提取结果必须以JSON数组格式输出
        2. 每个实体必须包含 name 和 type 字段，description 字段可选但强烈建议提供
        3. 确保 type 字段的值必须严格从 EntityTypes 列表中选择，不得创建新类型
        4. 如果无法确定实体类型，不要强行归类，宁可不提取该实体
        5. 不要输出任何解释或额外内容，只输出JSON数组
        6. 所有字段值不能包含HTML标签或其他代码
        7. 如果实体有歧义，需在description中说明具体指代
        8. 若没有找到任何实体，返回空数组 []

        ## 实体提取规则
        - Person: 真实或虚构的人物，包括历史人物、现代人物、文学角色等
        - Organization: 公司、政府机构、团队、学校等组织实体
        - Location: 地理位置、地标、国家、城市等
        - Product: 商品、服务、品牌等商业产品
        - Event: 事件、会议、节日、历史事件等
        - Date: 日期、时间段、年代等时间相关信息
        - Work: 书籍、电影、音乐、艺术作品等创作内容
        - Concept: 抽象概念、思想、理论等
        - Resource: 自然资源、信息资源、工具等
        - Category: 分类、类别、领域等
        - Operation: 操作、动作、方法、过程等

        ## 提取步骤
        1. 仔细阅读文本，识别可能的实体
        2. 对每个识别到的实体，确定其最适合的实体类型（必须从EntityTypes中选择）
        3. 为每个实体创建包含以下字段的JSON对象：
           - name: 实体的标准名称，不包含修饰词，如引号等
           - type: 从EntityTypes中选择的实体类型
           - description: 对该实体的简明中文描述，应基于文本内容
        4. 验证每个实体的所有字段是否正确且格式化恰当
        5. 将所有实体对象合并为一个JSON数组
        6. 检查最终JSON是否有效并符合要求

        ## 示例
        [输入]
        文本： 《红楼梦》，又名《石头记》，是清代作家曹雪芹创作的中国古典四大名著之一，被誉为中国封建社会的百科全书。该书前80回由曹雪芹所著，后40回一般认为是高鹗所续。小说以贾、史、王、薛四大家族的兴衰为背景，以贾宝玉、林黛玉和薛宝钗的爱情悲剧为主线，刻画了以贾宝玉和金陵十二钗为中心的正邪两赋、贤愚并出的高度复杂的人物群像。成书于乾隆年间（1743年前后），是中国文学史上现实主义的高峰，对后世影响深远。

        [输出]
        [
          {
            "name": "红楼梦",
            "type": "Work",
            "description": "红楼梦是清代作家曹雪芹创作的中国古典四大名著之一，被誉为中国封建社会的百科全书"
          },
          {
            "name": "石头记",
            "type": "Work",
            "description": "石头记是红楼梦的别名"
          },
          {
            "name": "曹雪芹",
            "type": "Person",
            "description": "曹雪芹是清代作家，红楼梦的作者，创作了前80回"
          },
          {
            "name": "高鹗",
            "type": "Person",
            "description": "高鹗是红楼梦后40回的续作者"
          },
          {
            "name": "贾宝玉",
            "type": "Person",
            "description": "贾宝玉是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "林黛玉",
            "type": "Person",
            "description": "林黛玉是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "薛宝钗",
            "type": "Person",
            "description": "薛宝钗是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "金陵十二钗",
            "type": "Concept",
            "description": "金陵十二钗是红楼梦中以贾宝玉为中心的十二位主要女性角色"
          },
          {
            "name": "乾隆年间",
            "type": "Date",
            "description": "乾隆年间指的是红楼梦成书的时间，约1743年前后"
          },
          {
            "name": "四大家族",
            "type": "Concept",
            "description": "四大家族是红楼梦中的贾、史、王、薛四个家族，是小说的背景"
          },
          {
            "name": "中国文学史",
            "type": "Category",
            "description": "红楼梦被视为中国文学史中现实主义的高峰之作"
          }
        ]

  relationPrompt: |
    ## 任务
        从用户提供的实体数组中，提取实体之间存在的明确关系，形成结构化的关系网络。

        ## 要求
        1. 关系提取必须基于提供的文本内容，不得臆测不存在的关系
        2. 结果必须以JSON数组格式输出，每个关系为数组中的一个对象
        3. 每个关系对象必须包含 source, target, description 和 strength 字段
        4. 不要输出任何解释或额外内容，只输出JSON数组
        5. 若没有找到任何关系，返回空数组 []

        ## 关系提取规则
        - 只有在文本中明确体现的关系才应被提取
        - 源实体(source)和目标实体(target)必须是实体数组中已有的实体
        - 关系描述(description)应简明扼要地说明两个实体间的具体关系
        - 关系强度(strength)应根据以下标准确定：
          * 10分：直接创造/从属关系（如作者与作品、发明者与发明、母公司与子公司）
          * 9分：同一实体的不同表现形式（如别名、曾用名）
          * 8分：紧密相关且互相影响的关系（如密切合作伙伴、家庭成员）
          * 7分：明确但非直接的关系（如作品中的角色、组织中的成员）
          * 6分：间接关联且有明确联系（如同事关系、相似产品）
          * 5分：存在关联但较为松散（如同一领域的不同概念）

        ## 提取步骤
        1. 仔细分析文本内容，确定哪些实体之间存在明确关系
        2. 只考虑文本中明确提及的关系，不要臆测
        3. 对每个找到的关系，确定：
           - source: 关系的源实体标题（必须是实体列表中已有的实体）
           - target: 关系的目标实体标题（必须是实体列表中已有的实体）
           - description: 简明准确的关系描述（用中文表述）
           - strength: 基于上述标准的关系强度（5-10之间的整数）
        4. 检查每个关系是否双向：
           - 如果关系是双向的（如"A是B的朋友"意味着"B也是A的朋友"），考虑是否需要创建反向关系
           - 如果关系是单向的（如"A创作了B"），则只保留单向关系
        5. 验证所有关系的一致性和合理性：
           - 确保没有矛盾的关系（如A同时是B的父亲和兄弟）
           - 确保关系描述与关系强度匹配
        6. 将所有有效关系组织为JSON数组

        ## 示例
        [输入]
        实体： [
          {
            "name": "红楼梦",
            "type": "Work",
            "description": "红楼梦是清代作家曹雪芹创作的中国古典四大名著之一，被誉为中国封建社会的百科全书"
          },
          {
            "name": "石头记",
            "type": "Work",
            "description": "石头记是红楼梦的别名"
          },
          {
            "name": "曹雪芹",
            "type": "Person",
            "description": "曹雪芹是清代作家，红楼梦的作者，创作了前80回"
          },
          {
            "name": "高鹗",
            "type": "Person",
            "description": "高鹗是红楼梦后40回的续作者"
          },
          {
            "name": "贾宝玉",
            "type": "Person",
            "description": "贾宝玉是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "林黛玉",
            "type": "Person",
            "description": "林黛玉是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "薛宝钗",
            "type": "Person",
            "description": "薛宝钗是红楼梦中的主要角色，爱情悲剧的主角之一"
          },
          {
            "name": "四大家族",
            "type": "Concept",
            "description": "四大家族是红楼梦中的贾、史、王、薛四个家族，是小说的背景"
          },
          {
            "name": "金陵十二钗",
            "type": "Concept",
            "description": "金陵十二钗是红楼梦中以贾宝玉为中心的十二位主要女性角色"
          },
          {
            "name": "乾隆年间",
            "type": "Date",
            "description": "乾隆年间指的是红楼梦成书的时间，约1743年前后"
          },
          {
            "name": "中国文学史",
            "type": "Category",
            "description": "红楼梦被视为中国文学史中现实主义的高峰之作"
          }
        ]

        文本： 《红楼梦》，又名《石头记》，是清代作家曹雪芹创作的中国古典四大名著之一，被誉为中国封建社会的百科全书。该书前80回由曹雪芹所著，后40回一般认为是高鹗所续。小说以贾、史、王、薛四大家族的兴衰为背景，以贾宝玉、林黛玉和薛宝钗的爱情悲剧为主线，刻画了以贾宝玉和金陵十二钗为中心的正邪两赋、贤愚并出的高度复杂的人物群像。成书于乾隆年间（1743年前后），是中国文学史上现实主义的高峰，对后世影响深远。

        [输出]
        [
          {
            "source": "曹雪芹",
            "target": "红楼梦",
            "description": "曹雪芹是红楼梦的主要作者，创作了前80回",
            "strength": 10
          },
          {
            "source": "高鹗",
            "target": "红楼梦",
            "description": "高鹗是红楼梦后40回的续作者",
            "strength": 10
          },
          {
            "source": "红楼梦",
            "target": "石头记",
            "description": "石头记是红楼梦的别名",
            "strength": 9
          },
          {
            "source": "红楼梦",
            "target": "中国文学史",
            "description": "红楼梦被视为中国文学史中现实主义的高峰之作",
            "strength": 7
          },
          {
            "source": "贾宝玉",
            "target": "林黛玉",
            "description": "贾宝玉与林黛玉有深厚的爱情关系，是小说主线之一",
            "strength": 8
          },
          {
            "source": "贾宝玉",
            "target": "薛宝钗",
            "description": "贾宝玉与薛宝钗的关系是小说爱情悲剧主线的一部分",
            "strength": 8
          },
          {
            "source": "贾宝玉",
            "target": "金陵十二钗",
            "description": "贾宝玉是金陵十二钗故事的中心人物",
            "strength": 8
          },
          {
            "source": "红楼梦",
            "target": "贾宝玉",
            "description": "贾宝玉是红楼梦中的主要角色",
            "strength": 7
          },
          {
            "source": "红楼梦",
            "target": "林黛玉",
            "description": "林黛玉是红楼梦中的主要角色",
            "strength": 7
          },
          {
            "source": "红楼梦",
            "target": "薛宝钗",
            "description": "薛宝钗是红楼梦中的主要角色",
            "strength": 7
          },
          {
            "source": "红楼梦",
            "target": "四大家族",
            "description": "四大家族是红楼梦的背景设定",
            "strength": 7
          },
          {
            "source": "红楼梦",
            "target": "金陵十二钗",
            "description": "金陵十二钗是红楼梦中的重要概念",
            "strength": 7
          },
          {
            "source": "红楼梦",
            "target": "乾隆年间",
            "description": "红楼梦成书于乾隆年间，约1743年前后",
            "strength": 6
          }
        ]