db:
  driver: mysql
postgres:
  dsn: host=127.0.0.1 user=postgres password=yourpassword dbname=yourdb port=5432 sslmode=disable
mysql:
  dsn: root:12345678@tcp(localhost:3306)/flowing?charset=utf8mb4&parseTime=True&loc=Local
redis:
  host: localhost
  port: 6379
  password:
  db: 0
server:
  port: 8585
logger:
  format: json
  level: debug
  path:
jwt:
  secret: abcd1234
fileStore: minio
minio:
  endpoint: localhost:9000
  accessKey: minioadmin
  secretKey: 12345678
  bucket: flowingdocs
